#pragma once

enum DIRECTION {DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN ,DIR_END};

enum OBJID {OBJ_PLAYER, OBJ_BULLET, OBJ_MONSTER, OBJ_BOSS, OBJ_MONSTER_BULLET, OBJ_MOUSE, OBJ_SHIELD,OBJ_WEAPON, OBJ_BUTTON, OBJ_END };
enum UIID {UI_HP, UI_INVEN, UI_PAGE, UI_END};
enum TYPE { TYPE_WEAPON_GUN, TYPE_WEAPON_COMANDO, TYPE_WEAPON_LASER, TYPE_END};

enum WEAPON_TYPE{ WEAPON_GUN, WEAPON_COMANDO, WEAPON_END};

enum SCENEID { SC_LOGO, SC_MENU, SC_EDIT, SC_STAGE, SC_END };

enum RENDERID { RENDER_BACKGROUND, RENDER_GAMEOBJECT, RENDER_EFFECT, RENDER_UI, RENDER_END };

// 최대 32개 채널까지 동시 재생이 가능
enum CHANNELID { SOUND_EFFECT, SOUND_BGM, SOUND_PLAYER, SOUND_MONSTER, MAXCHANNEL };